apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: exchange-deployment
  namespace: argocd

spec:
  generators:
    - list:
        elements:
        - name: api-app
          path: infra/api
        - name: ws-app
          path: infra/ws
        
  template:
    metadata:
      name: '{{.name}}-app'

    spec:
      project: exchange-app

      source:
        repoURL: https://github.com/gowdaganesh005/exchange.git
        targetRevision: HEAD
        path: '{{.path}}'

      destination:
        server: https://kubernetes.default.svc
        namespace: exchange
        