apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: api-service
spec:
  selector:
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: api-deployment
  ports:
    - protocol: TCP
      port: 80